### ISSUE TITLE
possible bug in Ranvec1 class version 2.0 under windows 10 x64 with Zen2 cpu?

### ISSUE THREAD

**Issue by ghost** [vectorclass/add-on#1]
Hi,
First of all, thanks for your great code!

I'm having a strange bug when using the version 2.0 of the ranvec1 class when using gentype 3 
under Windows10 x64 with the VS2019 compiler on a ryzen 3900x processor

The following code works flawless when using version 1.25 of the ranvec1 class:

static const Vec8f BernoulliVecFloat(const Float& keepRate)
{
	__declspec(align(64)) static thread_local Ranvec1* generator;

	if (!generator)
	{
		generator = new Ranvec1(3);
		generator->init(int(std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::high_resolution_clock::now().time_since_epoch()).count() + std::hash<std::thread::id>()(std::this_thread::get_id())));
	}
	return select((*generator).random8f() < keepRate, Vec8f(1), Vec8f(0));
}

I must make a small change to Ranvec1base class to get the aligment requirements right:
__declspec(align(64)) class Ranvec1base {
public:
    Ranvec1base(int gtype = 3);                    // Constructor
	void* operator new(size_t i)
	{
		return _aligned_malloc(i, 64);
	}
	void operator delete(void* p)
	{
		_aligned_free(p);
	}

The bug doesn't happen in Debug mode. And on a Intel Haswell platform it strangly doesn't occur!
Has this something to do with the problem Zen2 has with the rdrand instruction?

thanks

**Comment by AgnerF** [comment]
The code has no aligned read or write. Apparently, the compiler has put in some vector read or write instruction that requires alignment. Can the debugger point to the place of error? What instruction set are you compiling for?

Another thing is that you are using an inefficient way of thread local storage. Instead of making a thread_local pointer and allocating on the heap, you can just declare the Ranvec1 object in the thread function. That will put it on the stack, and each thread has its own stack.

**Comment by AgnerF** [comment]
I have added an example in ranvec1_manual.pdf showing how to make random numbers in multiple threads.

**Comment by ghost** [comment]
Thanks for the response and sample code!

Everything works now with version 2.0 of the vector and ranvec1 class.
I declare the Ranvec1 class in the threaded function as you said and the problems were gone. I didn't have to modify the Ranvec1base class anymore.

**Comment by AgnerF** [comment]
The error may still pop up again if the compiler makes an alignment error. Your initial code does not appear to be wrong - only slightly less efficient.
It would be nice if you can trace exactly where the error occurs.

**Comment by ghost** [comment]
When I use the original function with the latest version of the vector and Ranvec1 class I'm getting an  access violation read error when calling  the constructor: 
  generator = new Ranvec1(3);

Exception thrown at 0x00007FFF2299D10E (ntdll.dll) in Convnet.exe: 0xC0000005: Access violation reading location 0x0000018600000010.

I'm using c++17 and AVX2 instruction set enabled in vs2019 with all the latest updates.

I changed Ranvec1.h:
__declspec(align(64)) class Ranvec1base {
public:
Ranvec1base(int gtype = 3); // Constructor
void* operator new(size_t i)
{
return _aligned_malloc(i, 64);
}
void operator delete(void* p)
{
_aligned_free(p);
}

**Comment by ghost** [comment]
I changed Ranvec1.h again and also added __declspec(align(64)) to the Ranvec1 and Buf512 class with
void* operator new(size_t i)
{
return _aligned_malloc(i, 64);
}
void operator delete(void* p)
{
_aligned_free(p);
}

This seems to have solved the problem because the exception is gone now.

Oops the same error occurred again only now it take some time before it happens, at least the changes I've made did make the situation a bit better, 

I removed some leftover /favor:INTEL64 compiler settings because I'm running on a Zen2 processor.
I'm training a wide resnet with dropout using the Randvec1 class. It's running now for more than 30 minutes without an exception.

**Comment by ghost** [comment]
Sadly the bug is still there. But now the same compiled binaries run fine on a zen2 machine but give again the same excpetion on the intel Haswell (AVX2) machine. I also tried a compile with /favor:INTEL64 settings but without success. In Debug mode everything runs normal on the intel machine

**Comment by AgnerF** [comment]
I cannot reproduce your error. I cannot find the error without more detailed information from you. Try to compile for release mode and then press F5 (debug). This should point to the error and show a disassembly. This will show if the compiler has generated an aligned access where it is supposed to be unaligned.

I have now aligned Ranvec1base by 64 (cache line size). This might help, but I would still like to know if there is a compiler problem.

**Comment by ghost** [comment]
First of all sorry for the long delay.
When I compile in release and press F5 for debug. 

Exception thrown at 0x00007FFCAC3DD10E (ntdll.dll) in Convnet.exe: 0xC0000005: Access violation reading location 0x000001DE00000010.

diassembly:
00007FFCAC49919C  mov         qword ptr [rsp+18h],rbx  
00007FFCAC4991A1  mov         qword ptr [rsp+20h],rsi  
00007FFCAC4991A6  mov         qword ptr [rsp+10h],rdx  
00007FFCAC4991AB  push        rdi  
00007FFCAC4991AC  sub         rsp,0E0h  
00007FFCAC4991B3  mov         rax,qword ptr [7FFCAC51D4E0h]  
00007FFCAC4991BA  xor         rax,rsp  
00007FFCAC4991BD  mov         qword ptr [rsp+0D0h],rax  
00007FFCAC4991C5  mov         esi,r8d  
00007FFCAC4991C8  mov         rdi,rdx  
00007FFCAC4991CB  mov         ebx,ecx  
00007FFCAC4991CD  mov         dword ptr [rsp+20h],ecx  
00007FFCAC4991D1  call        00007FFCAC49914C  
00007FFCAC4991D6  test        al,al  
00007FFCAC4991D8  je          00007FFCAC499201  
00007FFCAC4991DA  mov         r9d,ecx  
00007FFCAC4991DD  lea         r8,[7FFCAC4D8290h]  
00007FFCAC4991E4  xor         edx,edx  
00007FFCAC4991E6  lea         ecx,[rdx+65h]  
00007FFCAC4991E9  call        00007FFCAC3F2110  
00007FFCAC4991EE  test        esi,esi  
00007FFCAC4991F0  je          00007FFCAC499201  
00007FFCAC4991F2  int         3                                            <================== cursor points to this line
00007FFCAC4991F3  jmp         00007FFCAC499201  
00007FFCAC4991F5  mov         rdi,qword ptr [rsp+0F8h]  
00007FFCAC4991FD  mov         ebx,dword ptr [rsp+20h]  
00007FFCAC499201  mov         dword ptr [rsp+30h],ebx  
00007FFCAC499205  mov         ecx,1  
00007FFCAC49920A  mov         dword ptr [rsp+34h],ecx  
00007FFCAC49920E  and         qword ptr [rsp+38h],0  
00007FFCAC499214  lea         rax,[7FFCAC409E90h]  
00007FFCAC49921B  mov         qword ptr [rsp+40h],rax  
00007FFCAC499220  mov         dword ptr [rsp+48h],ecx  
00007FFCAC499224  mov         qword ptr [rsp+50h],rdi  
00007FFCAC499229  lea         rcx,[rsp+30h]  
00007FFCAC49922E  call        00007FFCAC499260  
00007FFCAC499233  mov         rcx,qword ptr [rsp+0D0h]  
00007FFCAC49923B  xor         rcx,rsp  
00007FFCAC49923E  call        00007FFCAC42C150  
00007FFCAC499243  lea         r11,[rsp+0E0h]  
00007FFCAC49924B  mov         rbx,qword ptr [r11+20h]  
00007FFCAC49924F  mov         rsi,qword ptr [r11+28h]  
00007FFCAC499253  mov         rsp,r11  
00007FFCAC499256  pop         rdi  
00007FFCAC499257  ret  
00007FFCAC499258  int         3  
00007FFCAC499259  int         3  
00007FFCAC49925A  int         3  
00007FFCAC49925B  int         3  
00007FFCAC49925C  int         3  
00007FFCAC49925D  int         3  
00007FFCAC49925E  int         3  
00007FFCAC49925F  int         3  


When i load some missing symbol files I get:

RtlIsNonEmptyDirectoryReparsePointAllowed:
00007FFCAC499180  bt          ecx,1Ch  
00007FFCAC499184  jb          RtlIsNonEmptyDirectoryReparsePointAllowed+11h (07FFCAC499191h)  
00007FFCAC499186  cmp         ecx,80000018h  
00007FFCAC49918C  je          RtlIsNonEmptyDirectoryReparsePointAllowed+11h (07FFCAC499191h)  
00007FFCAC49918E  xor         al,al  
00007FFCAC499190  ret  
00007FFCAC499191  mov         al,1  
00007FFCAC499193  ret  
00007FFCAC499194  int         3  
00007FFCAC499195  int         3  
00007FFCAC499196  int         3  
00007FFCAC499197  int         3  
00007FFCAC499198  int         3  
00007FFCAC499199  int         3  
00007FFCAC49919A  int         3  
00007FFCAC49919B  int         3  
RtlReportCriticalFailure:
00007FFCAC49919C  mov         qword ptr [rsp+18h],rbx  
00007FFCAC4991A1  mov         qword ptr [rsp+20h],rsi  
00007FFCAC4991A6  mov         qword ptr [rsp+10h],rdx  
00007FFCAC4991AB  push        rdi  
00007FFCAC4991AC  sub         rsp,0E0h  
00007FFCAC4991B3  mov         rax,qword ptr [__security_cookie (07FFCAC51D4E0h)]  
00007FFCAC4991BA  xor         rax,rsp  
00007FFCAC4991BD  mov         qword ptr [rsp+0D0h],rax  
00007FFCAC4991C5  mov         esi,r8d  
00007FFCAC4991C8  mov         rdi,rdx  
00007FFCAC4991CB  mov         ebx,ecx  
00007FFCAC4991CD  mov         dword ptr [rsp+20h],ecx  
00007FFCAC4991D1  call        RtlIsAnyDebuggerPresent (07FFCAC49914Ch)  
00007FFCAC4991D6  test        al,al  
00007FFCAC4991D8  je          RtlReportCriticalFailure+65h (07FFCAC499201h)  
00007FFCAC4991DA  mov         r9d,ecx  
00007FFCAC4991DD  lea         r8,[string "Critical error detected %lx\n" (07FFCAC4D8290h)]  
00007FFCAC4991E4  xor         edx,edx  
00007FFCAC4991E6  lea         ecx,[rdx+65h]  
00007FFCAC4991E9  call        DbgPrintEx (07FFCAC3F2110h)  
00007FFCAC4991EE  test        esi,esi  
00007FFCAC4991F0  je          RtlReportCriticalFailure+65h (07FFCAC499201h)  
00007FFCAC4991F2  int         3     <=================================== cursor point to this line
00007FFCAC4991F3  jmp         RtlReportCriticalFailure+65h (07FFCAC499201h)  
00007FFCAC4991F5  mov         rdi,qword ptr [rsp+0F8h]  
00007FFCAC4991FD  mov         ebx,dword ptr [rsp+20h]  
00007FFCAC499201  mov         dword ptr [rsp+30h],ebx  
00007FFCAC499205  mov         ecx,1  
00007FFCAC49920A  mov         dword ptr [rsp+34h],ecx  
00007FFCAC49920E  and         qword ptr [rsp+38h],0  
00007FFCAC499214  lea         rax,[RtlRaiseException (07FFCAC409E90h)]  
00007FFCAC49921B  mov         qword ptr [rsp+40h],rax  
00007FFCAC499220  mov         dword ptr [rsp+48h],ecx  
00007FFCAC499224  mov         qword ptr [rsp+50h],rdi  
00007FFCAC499229  lea         rcx,[rsp+30h]  
00007FFCAC49922E  call        RtlReportFatalFailure (07FFCAC499260h)  
00007FFCAC499233  mov         rcx,qword ptr [rsp+0D0h]  
00007FFCAC49923B  xor         rcx,rsp  
00007FFCAC49923E  call        __security_check_cookie (07FFCAC42C150h)  
00007FFCAC499243  lea         r11,[rsp+0E0h]  
00007FFCAC49924B  mov         rbx,qword ptr [r11+20h]  
00007FFCAC49924F  mov         rsi,qword ptr [r11+28h]  
00007FFCAC499253  mov         rsp,r11  
00007FFCAC499256  pop         rdi  
00007FFCAC499257  ret  
00007FFCAC499258  int         3  
00007FFCAC499259  int         3  
00007FFCAC49925A  int         3  
00007FFCAC49925B  int         3  
00007FFCAC49925C  int         3  
00007FFCAC49925D  int         3  
00007FFCAC49925E  int         3  
00007FFCAC49925F  int         3  
RtlReportFatalFailure:
00007FFCAC499260  sub         rsp,48h  
00007FFCAC499264  call        RtlRaiseException (07FFCAC409E90h)  
00007FFCAC499269  jmp         RtlReportFatalFailure+0Bh (07FFCAC49926Bh)  
00007FFCAC49926B  add         rsp,48h  
00007FFCAC49926F  ret  
00007FFCAC499270  push        rbp

**Comment by ghost** [comment]
When running with the new ranvec1.h header:

Critical error detected c0000374


RtlReportCriticalFailure:
00007FFCAC49919C  mov         qword ptr [rsp+18h],rbx  
00007FFCAC4991A1  mov         qword ptr [rsp+20h],rsi  
00007FFCAC4991A6  mov         qword ptr [rsp+10h],rdx  
00007FFCAC4991AB  push        rdi  
00007FFCAC4991AC  sub         rsp,0E0h  
00007FFCAC4991B3  mov         rax,qword ptr [__security_cookie (07FFCAC51D4E0h)]  
00007FFCAC4991BA  xor         rax,rsp  
00007FFCAC4991BD  mov         qword ptr [rsp+0D0h],rax  
00007FFCAC4991C5  mov         esi,r8d  
00007FFCAC4991C8  mov         rdi,rdx  
00007FFCAC4991CB  mov         ebx,ecx  
00007FFCAC4991CD  mov         dword ptr [rsp+20h],ecx  
00007FFCAC4991D1  call        RtlIsAnyDebuggerPresent (07FFCAC49914Ch)  
00007FFCAC4991D6  test        al,al  
00007FFCAC4991D8  je          RtlReportCriticalFailure+65h (07FFCAC499201h)  
00007FFCAC4991DA  mov         r9d,ecx  
00007FFCAC4991DD  lea         r8,[string "Critical error detected %lx\n" (07FFCAC4D8290h)]  
00007FFCAC4991E4  xor         edx,edx  
00007FFCAC4991E6  lea         ecx,[rdx+65h]  
00007FFCAC4991E9  call        DbgPrintEx (07FFCAC3F2110h)  
00007FFCAC4991EE  test        esi,esi  
00007FFCAC4991F0  je          RtlReportCriticalFailure+65h (07FFCAC499201h)  
00007FFCAC4991F2  int         3           <======================> points to this
00007FFCAC4991F3  jmp         RtlReportCriticalFailure+65h (07FFCAC499201h)  
00007FFCAC4991F5  mov         rdi,qword ptr [rsp+0F8h]  
00007FFCAC4991FD  mov         ebx,dword ptr [rsp+20h]  
00007FFCAC499201  mov         dword ptr [rsp+30h],ebx  
00007FFCAC499205  mov         ecx,1  
00007FFCAC49920A  mov         dword ptr [rsp+34h],ecx  
00007FFCAC49920E  and         qword ptr [rsp+38h],0  
00007FFCAC499214  lea         rax,[RtlRaiseException (07FFCAC409E90h)]  
00007FFCAC49921B  mov         qword ptr [rsp+40h],rax  
00007FFCAC499220  mov         dword ptr [rsp+48h],ecx  
00007FFCAC499224  mov         qword ptr [rsp+50h],rdi  
00007FFCAC499229  lea         rcx,[rsp+30h]  
00007FFCAC49922E  call        RtlReportFatalFailure (07FFCAC499260h)  
00007FFCAC499233  mov         rcx,qword ptr [rsp+0D0h]  
00007FFCAC49923B  xor         rcx,rsp  
00007FFCAC49923E  call        __security_check_cookie (07FFCAC42C150h)  
00007FFCAC499243  lea         r11,[rsp+0E0h]  
00007FFCAC49924B  mov         rbx,qword ptr [r11+20h]  
00007FFCAC49924F  mov         rsi,qword ptr [r11+28h]  
00007FFCAC499253  mov         rsp,r11  
00007FFCAC499256  pop         rdi  
00007FFCAC499257  ret  
00007FFCAC499258  int         3  
00007FFCAC499259  int         3  
00007FFCAC49925A  int         3  
00007FFCAC49925B  int         3  
00007FFCAC49925C  int         3  
00007FFCAC49925D  int         3  
00007FFCAC49925E  int         3  
00007FFCAC49925F  int         3  
RtlReportFatalFailure:

**Comment by ghost** [comment]
Hi,

I've found the culprit of all these exceptions and weird behavior. MAX_VECTOR_SIZE was having the value of 512 instead of 256. This was because I've added the /add-on/random directory in the list of Include Directories in the visual studio project configuration. Simply by removing the line all my troubles were gone. By adding this directory MAX_VECTOR_SIZE gets the default of 512 from the vectorclass.h header.

Sorry for all the inconvenience but I'm glad I can use the most recent vectorclass code now! 
My code is a bit faster with the new vectorclass and Ranvec1 classes compared with the latest pre-github code.
