### ISSUE TITLE
Efficient way to convert between interleaved and seperate real/imag

### ISSUE THREAD

**Issue by robinchrist** [vectorclass/add-on#4]
Hi,

I think it would be very useful if there was a built-in utility to convert between `Vec4f real, Vec4f imag -> Complex4f complexVec` and vice-versa, i.e. `Complex4f complexVec -> Vec4f real, Vec4f imag`.

Sometimes you maybe want to use `atan2` which requires separate x and y vectors, or have to do some calculations on complex numbers which are stored in seperate real / imag arrays because your function is called from an external library, etc...

**Comment by AgnerF** [comment]
Try this
```
#include "vectorclass.h"
#include "vectormath_trig.h"
#include "complexvec1.h"
...

    Complex4f a = ...
    // separate real and imaginary parts
    Vec8f b = permute8<0,2,4,6,1,3,5,7>(a.to_vector());
    Vec4f re = b.get_low();
    Vec4f im = b.get_high();
    Vec4f angle = atan2(im,re);
    Vec4f radius = sqrt(re*re + im*im);
    // join real and imag parts back together
    Vec8f c = permute8<0,4,1,5,2,6,3,7>(Vec8f(re,im));
    Complex4f d = Complex4f(c);  // d = a
```

**Comment by robinchrist** [comment]
I know this way and I also use it, but I think it would be more intuitive and comfortable if you wouldn't have to do this "manually".

**Comment by AgnerF** [comment]
It is awkward to make a function with two return values in C++. But it may be useful to have a few examples in the manual showing how to separate real and imaginary parts.

**Comment by robinchrist** [comment]
I thought about something like

```
Vec16f to_deinterleaved_vector() const {
    return permute16<0, 2, 4, 6, 8, 10, 12, 14, 1, 3, 5, 7, 9, 11, 13, 15>(y);
}
```

This would drastically reduce the probability of typos in the template argument (and thus bugs which are quite difficult to track down).

I also think it's efficient enough:
https://godbolt.org/z/-zqz6U
Clang generates the same code for the first three variants, but seems to be confused by the fourth.
Which do you think would be the most efficient?
I suppose the 
```
        vmovaps ymmword ptr [rsi], ymm2
        vmovaps ymmword ptr [rdx], ymm0
        vzeroupper
```
would disappear in practice when the function is inlined by the compiler.

For AVX512 instruction set, there are differences in the generated code:
https://godbolt.org/z/ejkGYL

**Comment by AgnerF** [comment]
Functions to interleave and split into real and imag parts are added now
