### ISSUE TITLE
const pointer parameter for load method in vector_containers.h

### ISSUE THREAD

**Issue by RayZ0rr** [vectorclass/add-on#7]
When the load method is called, the elements in the corresponding array in not modified. So, the function parameters should be const.

This is the case for the vectorclass members where:
```
load(const pointer
```
is the signature.

Since, [load method](https://github.com/vectorclass/add-on/blob/cbba6b2f6e171b290b2df4b7aee0916a293d2e6e/containers/vector_containers.h#L98) of [ContainerV](https://github.com/vectorclass/add-on/blob/master/containers/vector_containers.h) just calls this iteratively, this change can be made.

**Comment by AgnerF** [comment]
Fixed
